### ISSUE TITLE
problem to get encoded URL as a query param

### ISSUE THREAD

**Issue by macroramesh6** [kadirahq/flow-router#465]
I have to redirect the previous location with some logic. so I came up to pass ReturnUrl as a query param.

for eg:
1. /users/edit/4?returnurl=/users/list
`FlowRouter.getQueryParam('returnurl'); // "/users/list"` *works fine*
2. /users/edit/4?returnurl=/users/list?page=10 
 `FlowRouter.getQueryParam('returnurl'); // "/users/list?page=10"` *works fine*
3. /users/edit/4?returnurl=/users/list?page=10&sort=new
 `FlowRouter.getQueryParam('returnurl'); // "/users/list?page=10"` *failed*

so I have tried to encode the url.

* /users/edit/4?returnurl=%2Fusers%2Flist%3Fpage%3D10%26sort%3Dnew
`FlowRouter.getQueryParam('returnurl'); // "/users/list?page=10"` *again failed*

Is there a way to fix this issue?

**Comment by todda00** [comment]
I am also having issues with encoded parameters not working, here is my example which has an encoded & (%26):

URL is: `http://localhost:3000/files?path=%2FDAN14-223%20BR%20R%26P%20Gearing%20Brochure%20FR`

The queryParams object is being stored as:
`Object {path: "/DAN14-223 BR R", P Gearing Brochure FR: ""}`

Seems like the url must be being decoded before creating the parameter object.

**Comment by todda00** [comment]
My issue with this was resolved when using kadira:flow-router-ssr

**Comment by arunoda** [comment]
Yes. We fixed some issues.

**Comment by tab00** [comment]
This is definitely a bug and it still doesn't fully work. Iron Router correctly decodes the query string. After changing my router to Flow Router only because it is now the officially-endorsed router, the query string decoding stopped working.

e.g. here is original data before encoding into the query string:
U2FsdGVkX1/3na5R9vbwHri1NrxdrwtwpGu9BOg+YcGik//DIUJSikPjG6n3rTWj44yxRuGsqMVqFCWun21m+/En

Here is data after encoding to query string and ready to use in URL:
U2FsdGVkX1%2F3na5R9vbwHri1NrxdrwtwpGu9BOg%2BYcGik%2F%2FDIUJSikPjG6n3rTWj44yxRuGsqMVqFCWun21m%2B%2FEn

Here is the data returned by FlowRouter.getQueryParam("data"):
U2FsdGVkX1/3na5R9vbwHri1NrxdrwtwpGu9BOg YcGik//DIUJSikPjG6n3rTWj44yxRuGsqMVqFCWun21m /En

It appears that the plus characters (+) became space characters.

It's quite a serious bug as we can't have data becoming corrupted when it is transmitted via query strings.

Please fix this as soon as possible.

Thank you.

**Comment by tab00** [comment]
How is the fix to this issue progressing?

**Comment by stinghz** [comment]
It appears that the plus characters (+) became space characters.

+1

**Comment by hacknlove** [comment]
```
FlowRouter.setQueryParams({test:'foo+bar'})
true

FlowRouter.getQueryParam('test')
"foo bar"
```

**Comment by arsenalol1** [comment]
The issue is not fixed yet... How is the fix to this issue progressing please? 

Thanks

**Comment by MathieuDerelle** [comment]
you need to do it manually with npm [query-string](https://www.npmjs.com/package/query-string) : 

```
const queryString = require('query-string');
const search = FlowRouter.current().path.split('?')[1];
console.log(queryString.parse(search));
```

**Comment by kcasas** [comment]
The workaround that fixed it for me is using `%252B` to represent `+` on the path.

**Comment by haveaguess** [comment]
Ran a debugger, looks like it decodes the query params in Flow Router then hands them over to qs library they are using and that goes ahead and decodes again unnecessarily

**Comment by haveaguess** [comment]
So I think this captures the double decoding from the debug session:

First decode of query params when setting up context
![image](https://user-images.githubusercontent.com/85821/117552106-7196c080-b041-11eb-9720-c3ccce1e3c3b.png)

Then later when pulling it out of the context : 

![image](https://user-images.githubusercontent.com/85821/117552161-b4f12f00-b041-11eb-89c1-a86cdf4a3f33.png)

`qs` library does its own decode : 

![image](https://user-images.githubusercontent.com/85821/117552204-e36f0a00-b041-11eb-969b-8ea393ab77af.png)

**Comment by michaelcbrook** [comment]
This is an old issue, but I recently fixed this in the [flow-router-extra](https://github.com/VeliovGroup/flow-router) package, and maybe it could be applied here as well. This package from Kadira hasn't been updated in almost 5 years, so I'm not going to bother submitting a PR for it, but here is the fix in flow-router-extra for anyone who's interested:

https://github.com/veliovgroup/flow-router/pull/92

**Comment by haveaguess** [comment]
Thanks @michaelcbrook great contribution! 👏🏻 🎉
