### ISSUE TITLE
FlowRouter.getParam returns undefined after a FlowRouter.go

### ISSUE THREAD

**Issue by jensljungblad** [kadirahq/flow-router#486]
I have the following, most of which I grabbed from the Meteor Guide: http://guide.meteor.com/data-loading.html#organizing-subscriptions

```js
Template.lobby.onCreated(function() {
  this.gameId = () => FlowRouter.getParam("_id");

  this.autorun(() => {
    var game = Games.findOne(this.gameId());

    if (game.started) {
      FlowRouter.go("game", { _id: game._id });
    }
  });
});

Template.lobby.helpers({
  game: function() {
    return Games.findOne(Template.instance().gameId());
  }
});
```

Now, when `game.started` turns true, the `autorun` executes the `FlowRouter.go`. When this happens, apparently `FlowRouter.getParam("_id")` becomes undefined, even before the new page has rendered. This leads my `game` helper to become undefined as well which leads to a bunch of crashes in my templates which expect there to be a `game` context present. 

Is this a bug in FlowRouter or am I supposed to do this differently?

**Comment by arunoda** [comment]
I'd like to have a sample repo in this case.
Could you try this with the `kadira:flow-router-ssr` instead of Flow Router?
New development is going there.

**Comment by jensljungblad** [comment]
@arunoda Where can I find the docs for the SSR version? I suspect I need to turn off the actual SSR part since I'm using Blaze and not React..

**Comment by jensljungblad** [comment]
Sorry, my mistake, I was running the router on the server as well as the client, hence the errors. Using the SSR branch seems to have solved the issue!

**Comment by krizka** [comment]
I have a sample repo. You can see the behaviour by console messages while switching within routes in first line. Please look at it. 
We first receiving old route param in new route, and then new one, but template helper already was called with bad data.
https://github.com/krizka/flow-rerender/tree/master/client

**Comment by krizka** [comment]
In addition to previous answer, wanted to say, that changing
```const id = FlowRouter.getParam('id');```
```
FlowRouter.watchPathChange();
const id = FlowRouter.current().params.id;
```
Working better and always returned right params values, but autorun called twice anyway.

**Comment by arunoda** [comment]
@krizka I'll have a look on this.

**Comment by krizka** [comment]
Thanks. 
Sorry, can't deploy to meteor.com, it says 'temporary unavailable'.

**Comment by arunoda** [comment]
Hey @krizka I can't find anything wrong your code.
May be you should post a new issue with more info.

That's because the original issue of @jensljungblad is solved.

**Comment by krizka** [comment]
Ok. Thanks. I will try with new version and open new if not solved.

**Comment by krizka** [comment]
It is still here in 3.9.3. Will open new issue now. Please see in short time.

**Comment by krizka** [comment]
#528 created.
